### PR TITLE
Enable node 10+ installation

### PR DESCRIPTION
**Pull request by chorsley**
Remove node engine requirement to enable installation on node versions above 10.

### CODE REVIEW

**Comment by bendtherules** [comment]
Our Travis CI tests should match the engine requirements.

1. Please add recent versions to [travis.yml](https://github.com/bendtherules/webpack-strip-log-loader/blob/master/.travis.yml) - that should pass. Ex. node 10 to 14 is missing there.

2. Also, if we are removing minimum engine requirement, that should also be reflected in travis tests i.e. check if node<6 works in CI tests. I think one of the dependencies wasn't available below node6.

More reference here - https://github.com/UD-UD/webpack-strip-log-loader/issues/2#issuecomment-530006918

**Comment by bendtherules** [comment]
Please merge my master branch. Fixed some yarn issue.

CI link for your PR - https://travis-ci.com/github/bendtherules/webpack-strip-log-loader/pull_requests

For some reason, the CI results are not showing up here. But currently, build for this PR is failing for that yarn issue.

**Review by bendtherules — CHANGES_REQUESTED** [review]
Merge from master

**Comment by bendtherules** [comment]
@chorsley Let me know if you need some help here.
I merged your branch with master in a local test branch, and that is working fine. So we should be good to go after this.

**Comment by chorsley** [comment]
Both merged master, and upgraded the upath sub-dependency in the yarn.lock so it passes CI for node 10+.

**Review by bendtherules — APPROVED** [review]

**Comment by bendtherules** [comment]
@chorsley Looks good. Merged now 👍.

Thanks a lot for the discussion and PR. Really appreciate your efforts.

**Comment by bendtherules** [comment]
I will release it on npm soon and update here.

**Comment by bendtherules** [comment]
New minor version - 0.3.0 (https://www.npmjs.com/package/webpack-strip-log-loader) is released now

**Comment by chorsley** [comment]
Many thanks for all your efforts @bendtherules !

**Pull request merged**
