### PR TITLE
upac now supports node > 9

### LINKED ISSUE #2: Did you make version for node >= 10?

### PR DESCRIPTION
**Pull request by Noitidart**
Resolves: https://github.com/UD-UD/webpack-strip-log-loader/issues/2

### CODE REVIEW

**Comment by bendtherules** [comment]
Remove engines in package.json to resolve current error

**Comment by Noitidart** [comment]
Thanks for that, done.

**Comment by Noitidart** [comment]
Weird so its still having that issue.

**Comment by bendtherules** [comment]
Now its happening because of "upath" module's engine configuration - which
was the original problem.

We need to check if there is some way to avoid that. Its a nested
dependency

**Comment by Noitidart** [comment]
Oh gosh, thanks for working with me.

**Comment by bendtherules** [comment]
Closing this PR now. PR #3 will fix this once merged.

Thanks for taking the initiative. I really appreciate your effort in contributing to this repo.

**Comment by Noitidart** [comment]
Thank you very much! You did all the heavy lifting!

**Pull request closed without merging**
