### PR TITLE
Allow side-effect import + module name pattern macthing

### PR DESCRIPTION
**Pull request by bendtherules**
Covers following use cases:
1. Relative import
2. Asset import (non-js)
3. Side-effect import (like `import 'something'`)

using both exact and pattern string matching.

Inspired by https://github.com/UD-UD/webpack-strip-log-loader/issues/3

### CODE REVIEW

**Comment by Noitidart** [comment]
> 
> 
> Covers following use cases:
> 
>     1. Relative import
> 
>     2. Asset import (non-js)
> 
> 
> using both exact and pattern string matching.
> 
> Inspired by [UD-UD#3](https://github.com/UD-UD/webpack-strip-log-loader/issues/3)

Thanks for the inspired by!! :)

**Comment by Noitidart** [comment]
I did `npm i github:bendtherules/webpack-strip-log-loader#module-name-matching -D` to install this branch then this is my config:

```
      output: {
        filename: '[name].bundle.js',
        library: 'component',
        libraryTarget: 'commonjs',
        path: path.resolve(__dirname, '../ssr'),
        publicPath: '/ssr/'
      },
      module: {
        rules: [
          {
            test: /\.js$/,
            exclude: /node_modules|dependencies/,
            use: [
              {
                loader: 'webpack-strip-log-loader',
                options: {
                  modules: ['*.css', '*.less']
                }
              },
              'babel-loader'
            ]
          }
        ]
      },
```

But I'm still getting errors :(

```
   ERROR in ./assets/js/components/SailsModal/index.less 1:0
    Module parse failed: Unexpected character '@' (1:0)
    You may need an appropriate loader to handle this file type.
    > @import '../../../styles/styleguide/colors.less';
    | @import '../../../styles/styleguide/typography.less';
    | @import '../../../styles/styleguide/buttons.less';
     @ ./assets/js/components/SailsModal/index.js 3:0-22
     @ ./assets/js/pages/account/account-overview.page.js
```

**Comment by bendtherules** [comment]
@Noitidart Currently, this branch only contains fix for side-effect import. Module name patterns are still not added. Will add it soon.

Try with `modules: ['./index.css', './index.less']`

**Comment by Noitidart** [comment]
Oh thank you! Trying now.

**Comment by Noitidart** [comment]
Yahoo that worked!!! Sincerest thanks brother!

**Comment by bendtherules** [comment]
Thanks. Will update here when the rest is fixed.

**Comment by bendtherules** [comment]
Should be working with globs now.

You can use any of these now:
A. `
{
    modules: ["./*.css", "./*.less"]
}
`
B. `
{
    modules: ["*.css", "*.less"],
    matchOptions: {
        matchBase: true
    }
}
`
C. `
{
    modules: ["*.@(css|less)"],
    matchOptions: {
        matchBase: true
    }
}
`

**Comment by Noitidart** [comment]
So so cool thank you!!! Will try it out!

**Comment by Noitidart** [comment]
Updated and tested with option B - `{ modules: ["*.css", "*.less"], matchOptions: { matchBase: true } }` working like a charm!! Thank you very much! I don't know why this lib is not more popular, I'm sure this is a common need, I wonder what others do.

**Comment by bendtherules** [comment]
I think most people use this - https://github.com/YahooArchive/strip-loader.

Its much more popular but currently unmaintained. I have used that earlier. It is regex-based, which in my opinion, makes it very unsafe for code manipulation.

This module can remove imports as well as usage of the imported variables/functions. So, lets say for styles if you were using css-modules (with jsx) like this - 

`
Import styles for 'a.css':

<div className={styles.abc} >
`
It would remove both the lines

**Comment by Noitidart** [comment]
Oh thank you for that. Yes removing the usage is more than half the battle.

**Comment by bendtherules** [comment]
Thanks for raising the issue and trying it out. I'll close the original issue once this is merged in master.

**Pull request merged**
